version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - API_PORT=${API_PORT:-3000}
    container_name: scandes-backend
    ports:
      - "${API_PORT:-3000}:${API_PORT:-3000}"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - API_PORT=${API_PORT:-3000}

